apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cl-dc3-qdt-01
  namespace: cl-dc3-qdt-01
spec:
  clusterName: cl-dc3-qdt-01
  clusterNamespace: cl-dc3-qdt-01
  clusterLabels:
    cloud: BareMetal
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
