---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: workernode2
  namespace: cl-dc3-qdt-01-infraenv
  labels:
    infraenvs.agent-install.openshift.io: cl-dc3-qdt-01
spec:
  interfaces:
    - name: ens1f0np0
      macAddress: '00:1B:2B:3C:4D:6E'
    - name: ens1f1np1
      macAddress: '00:1B:2B:3C:4D:7E'
    - name: ens2f0np1
      macAddress: '00:1B:2B:3C:4D:8E'
    - name: ens2f1np1
      macAddress: '00:1B:2B:3C:4D:9E'
  config:
    dns-resolver:
      config:
        server:
          - 10.210.20.24
          - 10.210.20.23
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.210.142.1
          next-hop-interface: bond0
          table-id: 254
    interfaces:
      - name: ens1f0np0
        type: ethernet
        state: up
        mac-address: '00:1B:2B:3C:4D:6E'
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: ens1f1np1
        type: ethernet
        state: up
        mac-address: '00:1B:2B:3C:4D:7E'
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: ens2f0np1
        type: ethernet
        state: up
        mac-address: '00:1B:2B:3C:4D:8E'
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: ens2f1np1
        type: ethernet
        state: up
        mac-address: '00:1B:2B:3C:4D:9E'
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: bond0
        type: bond
        state: up
        link-aggregation:
          mode: active-backup
          options:
            miimon: '100'
            primary: ens1f0np0
          port:
            - ens1f0np0
            - ens1f1np1
        ipv4:
          enabled: true
          address:
            - ip: 10.210.142.32
              prefix: 24
          dhcp: false
        ipv6:
          enabled: false
